# 중첩 가능 최대 버프 수, 1 이상 입력
maxStack: 3

# 최대 지속시간(초), -1이면 무한지속
duration: 10

# 효과 강도, 1 ~ 255 사이로 입력
amplifier: 3

# 등장 가능 효과 목록, 마인크래프트 명령어 형식대로 작성
effects:
  - "minecraft:speed"
  - "minecraft:haste"
  - "minecraft:jump_boost"
  - "minecraft:strength"
  - "minecraft:resistance"
  - "minecraft:regeneration"
  - "minecraft:fire_resistance"
  - "minecraft:water_breathing"
  - "minecraft:night_vision"
  - "minecraft:absorption"
  - "minecraft:health_boost"
  - "minecraft:saturation"
  - "minecraft:luck"
  - "minecraft:slow_falling"
  - "minecraft:conduit_power"
  - "minecraft:dolphins_grace"
  - "minecraft:instant_health"
  - "minecraft:invisibility"
  - "minecraft:hero_of_the_village"
  - "minecraft:slowness"
  - "minecraft:mining_fatigue"
  - "minecraft:nausea"
  - "minecraft:blindness"
  - "minecraft:hunger"
  - "minecraft:weakness"
  - "minecraft:poison"
  - "minecraft:wither"
  - "minecraft:instant_damage"
  - "minecraft:glowing"
  - "minecraft:levitation"
  - "minecraft:bad_omen"
  - "minecraft:darkness"
  - "minecraft:wind_charged"
  - "minecraft:weaving"
  - "minecraft:oozing"
  - "minecraft:infested"

# 포션 효과를 받을 음식 목록, 마인크래프트 명령어 형식대로 작성
foods:
  - "minecraft:apple"
  - "minecraft:golden_apple"
  - "minecraft:enchanted_golden_apple"
  - "minecraft:melon_slice"
  - "minecraft:sweet_berries"
  - "minecraft:glow_berries"
  - "minecraft:chorus_fruit"
  - "minecraft:carrot"
  - "minecraft:golden_carrot"
  - "minecraft:potato"
  - "minecraft:baked_potato"
  - "minecraft:poisonous_potato"
  - "minecraft:beetroot"
  - "minecraft:dried_kelp"
  - "minecraft:beef"
  - "minecraft:cooked_beef"
  - "minecraft:porkchop"
  - "minecraft:cooked_porkchop"
  - "minecraft:mutton"
  - "minecraft:cooked_mutton"
  - "minecraft:chicken"
  - "minecraft:cooked_chicken"
  - "minecraft:rabbit"
  - "minecraft:cooked_rabbit"
  - "minecraft:cod"
  - "minecraft:cooked_cod"
  - "minecraft:salmon"
  - "minecraft:cooked_salmon"
  - "minecraft:tropical_fish"
  - "minecraft:pufferfish"
  - "minecraft:bread"
  - "minecraft:cookie"
  - "minecraft:pumpkin_pie"
  - "minecraft:rotten_flesh"
  - "minecraft:spider_eye"
  - "minecraft:mushroom_stew"
  - "minecraft:beetroot_soup"
  - "minecraft:rabbit_stew"
  - "minecraft:suspicious_stew"
  - "minecraft:honey_bottle"
  - "minecraft:potion"